### ISSUE TITLE
can not open saferoom in interchange

### ISSUE THREAD

**Issue by yhl452493373** [dwesterwick/SPTOpenSesame#2]
can not open saferoom in interchange

**Comment by dwesterwick** [comment]
This occurs because the door is not operable, so there is no context menu for it. However, you can still use this mod to swipe the keypad in the Burger Spot restroom without needing the card. 

If you can figure out an easy way to create a context menu for the door, feel free to create a PR. However, since this is one of the few doors that doesn't work with this mod, I probably won't work on this for a while.

**Comment by yhl452493373** [comment]
I tried many times, there is no way for me.

**Comment by dwesterwick** [comment]
Thanks anyway for trying.
